# Generated by Django 5.0.2 on 2024-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_expense_created_at_alter_income_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
